### PR TITLE
Use /usr/bin/env ls instead of ls

### LINKED ISSUE #32: Unknown argument -A when installing pharos
When I execute: `chpharos install 1.3.1` I get:
```
Downloading 'pharos-cluster' (23854176 bytes) from https://get.pharos.sh/versions/download/pharos-cluster-linux-amd64-1.3.1 ..               
###################################################################################################################################### 100.0%
Verifying download SHA256 checksum.. OK                                                                                                      
Downloading 'kubectl' (55400930 bytes) from https://storage.googleapis.com/kubernetes-release/release/v1.11.1/bin/linux/amd64/kubectl ..     
###################################################################################################################################### 100.0%
Verifying download SHA256 checksum.. OK                                                                                                      
Unknown argument -A                                                                                                                          
error: installation failed, use: chpharos list-remote to get a list of available versions.
```

It is because https://github.com/kontena/chpharos/blob/8d51fdf077deea933ec78a38db8a9e509fbe02c1/share/chpharos/chpharos.sh#L394 uses `ls` instead of `/usr/bin/ls`. In my case ls is an alias of exa which does not have a -A option.

### PR DESCRIPTION
**Pull request by Sh4d1**
Fixes #32 

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

File: share/chpharos/chpharos.sh [hunk 1]
```diff
@@ -391,7 +391,7 @@ _chpharos_version_is_installed() {
   for item in "${PHAROS_VERSIONS[@]}"; do
     if [ "${version}" = "$item" ]; then
       local version_root="${CHPHAROS_ROOT}/versions/${version}"
-      [ -d "${version_root}" ] && [ ! -z "$(ls -A "${version_root}")" ] && return 0
+      [ -d "${version_root}" ] && [ ! -z "$(/usr/bin/ls -A "${version_root}")" ] && return 0
```
Comment (kke) [inline share/chpharos/chpharos.sh]: There's no `/usr/bin/ls` on many systems (checked MacOS, ubuntu 16.04). A better alternative would be to use `/usr/bin/env ls`.

**Comment by Sh4d1** [comment]
@kke changed!
